-- What is magnitude exploration?
-- Magnitude = ∑ [Measure] By [Dimension]

-- Find total customers by countries
SELECT
    country,
    COUNT(DISTINCT customer_number) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(DISTINCT customer_number) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(DISTINCT product_name) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    CAST(AVG(cost) AS DECIMAL(10, 2)) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    dp.category AS category,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT
    dc.customer_key AS customer_key,
    dc.first_name AS first_name,
    dc.last_name AS last_name,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY 
    dc.customer_key,
    dc.first_name,
    dc.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    dc.country AS country,
    SUM(fs.quantity) AS total_quantity
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_quantity DESC;